### PR TITLE
Input Syntax Idea

### PR DESCRIPTION
**Pull request by friedmud**
Ok - here is my rework of the input file syntax for specifying the different chemical reaction problems.  It's not finished yet, but I thought I would put it up here to get some discussion going before I go further.

The basic idea is that a `ReaktoroProblemUserObject` holds a chemistry problem and gives out `ChemicalState` objects that all the other objects (Kernels, BCs, AuxKernels, etc.) can use.

The syntax currently looks like this:

```
[Modules]
  [Reaktoro]
    [Problems]
      # active = right
      [bulk]
        family = LAGRANGE
        order = FIRST
        substance_names = 'H2O NaCl'
        substance_amounts = '1 0.1'
        substance_units = 'kg mol'
        temperature = 'temp'
        pressure = 'pressure'
      []
      [left]
        family = LAGRANGE
        order = FIRST
        substance_names = 'H2O'
        substance_amounts = '1.00000001'
        substance_units = 'kg'
        temperature = 'temp'
        pressure = 'pressure'
        boundary = 'left'
      []
    []
  []
[]
```

All of the AuxKernels, etc. get added automatically.

Also: I did all the work to get the Elements coming out (not just "species") and add the nonlinear variables for all of the Elements, etc.

What do you guys think?

### CODE REVIEW

**Comment by allanleal** [comment]
Thanks, Derek. I'll be able to comment on the input syntax right now, and the rest tomorrow (it's still Easter holiday here).

I would suggest something like this (I understand some changes might still be needed to conform with MOOSE rules for input definition):

```
[Modules]
  [Reaktoro]
    [EquilibriumProblem]
      temperature = '60 celsius'
      pressure = '300 bar'
      mix = '1 kg H2O'
      label = 'StateInteriorDomain'
    []
    [EquilibriumProblem]
      temperature = '60 celsius'
      pressure = '300 bar'
      mix = '1 kg H2O, 1 mol NaCl'
      label = 'StateBoundaryLeft'
    []
    # active = right
    [bulk]
      family = LAGRANGE
      order = FIRST
      chemicalstate = 'StateInteriorDomain'
    []
    [left]
      family = LAGRANGE
      order = FIRST
      chemicalstate = 'StateBoundaryLeft'
    []
  []
[]
```
In case the user needs finer grain of control, he could then add a `ChemicalSystem` block as follows (to specify the thermodynamic/chemical models for each phase, the exact species each phase should have, instead of automatically collected from a database, etc):

```
[Modules]
  [Reaktoro]
    [ChemicalSystem]
      [AqueousPhase]
        species = 'H2O(l) H+ OH- Cl- Na+ CO2(aq) HCO3- CO3--'
        chemicalmodel = 'DebyeHuckel'
      []
      [GaseousPhase]
        species = 'H2O(g) CO2(g)'
        chemicalmodel = 'PengRobinson'
      []
      [MineralPhases]
        minerals = 'Calcite Dolomite Quartz'
      []
    [] 

    [EquilibriumProblem]
      temperature = '60 celsius'
      pressure = '300 bar'
      mix = '1 kg H2O'
      label = 'StateInteriorDomain'
    []

    [EquilibriumProblem]
      temperature = '60 celsius'
      pressure = '300 bar'
      mix = '1 kg H2O, 1 mol NaCl'
      label = 'StateBoundaryLeft'
    []
    # active = right
    [bulk]
      family = LAGRANGE
      order = FIRST
      chemicalstate = 'StateInteriorDomain'
    []
    [left]
      family = LAGRANGE
      order = FIRST
      chemicalstate = 'StateBoundaryLeft'
    []
  []
[]
```

**Comment by permcody** [comment]
On Mon, Apr 2, 2018 at 4:05 AM Allan Leal <notifications@github.com> wrote:

> Thanks, Derek. I'll be able to comment on the input syntax right now, and
> the rest tomorrow (it's still Easter holiday here).
>
> I would suggest something like this (I understand some changes might still
> be needed to conform with MOOSE rules for input definition):
>
> [Modules]
>   [Reaktoro]
>     [EquilibriumProblem]
>       temperature = '60 celsius'
>       pressure = '300 bar'
>       mix = '1 kg H2O'
>       label = 'StateInteriorDomain'
>     []
>     [EquilibriumProblem]
>       temperature = '60 celsius'
>       pressure = '300 bar'
>       mix = '1 kg H2O, 1 mol NaCl'
>       label = 'StateBoundaryLeft'
>     []
>
>
This won't quite work as is, because MOOSE doesn't really care about the
actual structure, it cares about the fully-qualified paths to parameters.
So the parameters in each of these blocks would have the same duplicate
path (e.g. Modules/Reaktoro/EquilibriumProblem/temperature).

If you are going to need multiple problems, we'll have to have subblocks or
come up with a different way to name the blocks so that the paths are
unique.


>
>     # active = right
>     [bulk]
>       family = LAGRANGE
>       order = FIRST
>       chemicalstate = 'StateInteriorDomain'
>     []
>     [left]
>       family = LAGRANGE
>       order = FIRST
>       chemicalstate = 'StateBoundaryLeft'
>     []
>   []
> []
>
> In case the user needs finer grain of control, he could then add a
> ChemicalSystem block as follows (to specify the thermodynamic/chemical
> models for each phase, the exact species each phase should have, instead of
> automatically collected from a database, etc):
>
> [Modules]
>   [Reaktoro]
>     [ChemicalSystem]
>       [AqueousPhase]
>         species = 'H2O(l) H+ OH- Cl- Na+ CO2(aq) HCO3- CO3--'
>         chemicalmodel = 'DebyeHuckel'
>       []
>       [GaseousPhase]
>         species = 'H2O(g) CO2(g)'
>         chemicalmodel = 'PengRobinson'
>       []
>       [MineralPhases]
>         minerals = 'Calcite Dolomite Quartz'
>       []
>     []
>
>
With MOOSE, we usually use the "type" system so the blocks are just for
organization and naming, but the "type" tells the system what kinds of
objects to instantiate. That would help here a bit. Other than that, this
syntax is moving in the right direction.

**Comment by allanleal** [comment]
I see, I had this problem with YAML before (two nodes with the same key name). We could either use your `type` suggestion, or something like this:

```
 [EquilibriumProblem label=StateInteriorDomain]
   temperature = '60 celsius'
   pressure = '300 bar'
   mix = '1 kg H2O'
 []
 [EquilibriumProblem label=StateBoundaryLeft]
   temperature = '60 celsius'
   pressure = '300 bar'
   mix = '1 kg H2O, 1 mol NaCl'
 []
```

The `EquilibriumProblem` block is more generic. Perhaps what we want is a `FluidState` and a `FluidRockState`  blocks. The first computes the chemical state of a fluid, to be used as boundary condition (e.g., an inlet). The second is for computing the composition of fluids and rock, to be used as initial condition (we would need one block for each sub-domain if initial conditions are different across them). For example, consider the following usage:

```
[FluidState label=Inlet]
   temperature = '60 celsius'
   pressure = '300 bar'
   aqueous_phase_composition = '1 molal NaCl, 0.01 molal MgCl2'
[]

[FluidRockState label=InitialCondition]
   temperature = '40 celsius'
   pressure = '100 bar'
   porosity = 0.3
   fluid_saturations = '0.8 Aqueous, 0.2 Gaseous'
   mineral_volume_fractions = '0.1 Calcite, 0.9 Quartz'
   aqueous_phase_composition = '0.1 molal NaCl'
   gaseous_phase_composition = '0.9 CO2(g), 0.1 CH4(g)'
[]
```

Internally, the `FluidState` calculation generates a `ChemicalState` object with label `Inlet` (we'll need a `std::map<std::string, ChemicalState>`) that contains the composition of the fluid being injected on an inlet. The `FluidRockState` calculation generates a `ChemicalState` object with label `InitialCondition` that contains aqueous and gaseous fluids with the given saturations; a rock with the given mineral composition (0.9 m3/m3 of Quartz and 0.1 m3/m3 of Calcite); and the volume of rock is `1 - porosity`. The total volume of the system (sum of fluid and rock volumes) is 1 m3. This 1m3 volume scaling behavior is not available in `EquilibriumProblem` block.

Let me know what you think.

**Comment by friedmud** [comment]
@allanleal The "labels" in MOOSE syntax are the block names.  Then we specify the type using `type`.  This isn't so much a suggestion... as just the way the syntax is 😄 

What this maps to on the backend (i.e. what objects get created - who holds what data) is more fluid.

So: to translate your most recent syntax:

```conf
 [EquilibriumProblem label=StateInteriorDomain]
   temperature = '60 celsius'
   pressure = '300 bar'
   mix = '1 kg H2O'
 []
 [EquilibriumProblem label=StateBoundaryLeft]
   temperature = '60 celsius'
   pressure = '300 bar'
   mix = '1 kg H2O, 1 mol NaCl'
 []
```

Would be:

```conf
[Problems]
  [interior_state]
    type = EquilibriumProblem
    pressure = '300 bar'
    mix = '1 kg H2O'
  []
  [left_boundary]
   type = EquilibriumProblem
   temperature = '60 celsius'
   pressure = '300 bar'
   mix = '1 kg H2O, 1 mol NaCl'
  []
[]
```

That gets us back to similar syntax to what I've proposed here in the PR (with the added thing that we can't accept something that looks like `60 celsius` - so we need two lines... one for the value and one for the units (like in my original syntax up above).

**Comment by allanleal** [comment]
> @allanleal The "labels" in MOOSE syntax are the block names. Then we specify the type using type. This isn't so much a suggestion... as just the way the syntax is 

The MOOSE way of using `type` is fine. Just to clarify though: My idea was to loop through the blocks in the input file, an get all nodes that start with string `EquilibriumProblem`. Then, I would extract the string after `label=`, e.g., `StateInteriorDomain`, and use this as a tag for the resulting calculated `ChemicalState` object. I do this in my YAML-based scripts.

> That gets us back to similar syntax to what I've proposed here in the PR (with the added thing that we can't accept something that looks like 60 celsius - so we need two lines... one for the value and one for the units (like in my original syntax up above).

OK. I guess peacock will be able to simplify this input (I usually prefer less verbose, but I understand one line for values and another for units simplify programming - no need to further parse the string `1 kg H2O` or `60 celsius`). 

For the `ChemicalSystem` block (for future considerations), this should be outside the `Problems` block. Maybe we should call these `States` instead.

```
[ChemicalSystem]
   ...
[]
[States]
  [interior_state]
    type = EquilibriumProblem
    temperature_value = 40
    temperature_units = 'celsius'
    pressure_value = 100
    pressure_units = 'bar'
    mixture_substances = 'H2O'
    mixture_amounts = '1'
    mixture_units = 'kg'
  []
  [left_boundary]
    type = EquilibriumProblem
    temperature_value = 60
    temperature_units = 'celsius'
    pressure_value = 300
    pressure_units = 'bar'
    mixture_substances = 'H2O NaCl'
    mixture_amounts = '1 1'
    mixture_units = 'kg mol'
  []
[]
```

**Comment by friedmud** [comment]
I like the `States` idea - I'll try to incorporate that next.

Derek

**Pull request merged**
